version: 0.2

env: 
  variables: # Values set in CodeBuild configuration. Including explicit assignments here for readability. Technically, the variables can be used without this explicit assignment.
    TARGET_S3_BUCKET: ${TARGET_S3_BUCKET}

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci # npm ci installs packages referenced in the package-lock.json, effectively freezing the packages that are installed to specific versions.
      - npm install -g gatsby-cli
  build:
    run-as: Linux-user-name
    commands:
      - gatsby build
  post_build:
    run-as: Linux-user-name
    commands:
      - aws s3 sync ./public/ "s3://${TARGET_S3_BUCKET}" --acl=public-read --delete

cache:
  paths:
    - 'node_modules/**/*'